// Generated by tools/build-site.js. Do not commit.
window.ET_CONFIG = {"execUrl":"https://script.google.com/macros/s/AKfycbyvtY__lUMMnoKJTnf-7ufYUfH69gidVlo-013Xv_DN83PfUVEyZiP7DVY-v5LrH2xb/exec","siteUrl":"https://tsg-homes.github.io/TSG-Client-Pages/events/"};
